### ISSUE TITLE
Transpile go lang code into C code

### ISSUE THREAD

**Issue by olemis** [simelo/cgogen#1]
Similar in intent to https://github.com/lpereira/gomoku (but with target being C++) .

**Comment by stdevAlDen** [comment]
Generated code compiles. Tested on address.go, crypto.go and hash.go. There is still an issue in hash.go with struct Ripemd160 struct, requires inplaceRipemd160 function.

**Comment by stdevAlDen** [comment]
Fixed that last one. Genereted code compiles for address.go, crypto.go and hash.go.

**Comment by olemis** [comment]
@stdevEclipse this issue is aimed at generating C **source code** out of inpput go lang source code .

**Comment by olemis** [comment]
no
