### ISSUE TITLE
Add support to define GoSlice in generate config

### ISSUE THREAD

**Issue by m4yk3ldev** [simelo/cgogen#23]
## Expected Behavior
- By means of definition in the configuration file, define which are the SLICE

## Real behavior
- It must be opened manually in the library.

**Comment by olemis** [comment]
@stdevHan why config file for this ? can't this be accurately inferred from type ?

**Comment by m4yk3ldev** [comment]
@olemis because there are some that I give special treatment, and that's where I define them.

**Comment by olemis** [comment]
@stdevHan what special exactly ?

**Comment by m4yk3ldev** [comment]
@olemis the type byte[] example https://github.com/simelo/cgogen/blob/master/src/cmd/cgogen.go#L87

**Comment by olemis** [comment]
@stdevHan that's a slice , you should not add it in config but check whether it's a slice

**Comment by m4yk3ldev** [comment]
@olemis I understand you, let me check like this, I think it would be better
